# Generated by Django 5.0.7 on 2024-07-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matriculo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Matriculo',
            new_name='Matricula',
        ),
    ]
