# Generated by Django 5.0.4 on 2024-07-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('lancamento', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=256)),
            ],
        ),
    ]
