# Generated by Django 5.0.7 on 2024-09-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
