-- Sintaxe:
ALTER TABLE <nome-tabela>
DROP COLUMN <nome-coluna>
ADD 	<nome-coluna> <tipo-do-dado> [NOT NULL]
[NOT NULL WITH DEFAULT] 
RENAME <nome-coluna> <novo-nome-coluna>
MODIFY <nome-coluna> <tipo-do-dado> [NULL]
[NOT NULL]

-- CRIAR A TABELA
CREATE TABLE T_TESTE_DDL
(
    CD_TESTE    NUMBER(3)       NOT NULL ,
    NM_TESTE    VARCHAR2(30)    NOT NULL ,
    DS_TESTE    VARCHAR2(60)        NULL ,
    DT_TESTE    DATE                NULL
);
-- CHAVE PRIMARIA
   ALTER TABLE T_TESTE_DDL 
ADD CONSTRAINT PK_TESTE_DDL 
   PRIMARY KEY (CD_TESTE);
-- CONSTRAINT UNIQUE
   ALTER TABLE T_TESTE_DDL 
ADD CONSTRAINT UN_TESTE_DDL_NOME 
        UNIQUE (NM_TESTE);
   ALTER TABLE T_TESTE_DDL 
ADD CONSTRAINT UN_TESTE_DDL_DESC 
        UNIQUE (DS_TESTE);
        
-- ADIÇÃO DE UMA COLUNA A UMA TABELA EXISTENTE
ALTER TABLE T_TESTE_DDL ADD DS_EMAIL VARCHAR2(80);

-- ADIÇÃO DE DUAS OU MAIS COLUNAS A UMA TABELA EXISTENTE
ALTER TABLE T_TESTE_DDL 
  ADD ( DS_OBS1 VARCHAR2(50) NOT NULL, 
        DS_OBS2 VARCHAR2(50) );
        
 -- AUMENTANDO O TAMANHO DE UMA COLUNA EM UMA TABELA EXISTENTE
ALTER TABLE T_TESTE_DDL
     MODIFY DS_OBS1 VARCHAR2(80);       
     
    -- MODIFICANDO O TIPO DE DADO DE UMA COLUNA EM 
-- UMA TABELA EXISTENTE   
ALTER TABLE T_TESTE_DDL
     MODIFY NM_TESTE CHAR(30); 
     
    -- MODIFICANDO UMA COLUNA NULL (OPCIONAL) PARA NOT NULL (OBRIGATORIA)
ALTER TABLE T_TESTE_DDL
     MODIFY DS_TESTE NOT NULL; 
    
    
-- MODIFICANDO UMA COLUNA NOT NULL (OBRIGATORIA) 
-- PARA  NULL (OPCIONAL)
ALTER TABLE T_TESTE_DDL
     MODIFY DS_OBS1 NULL;    
    
    
-- MODIFICANDO TIPO DE DADO, TAMANHO E OBRIGATORIEDADE 
-- DE UMA COLUNA 
ALTER TABLE T_TESTE_DDL
     MODIFY NM_TESTE VARCHAR2(40) NULL;    
     

-- MODIFICANDO UM VALOR DEFAULT
-- SYSDATE -> FUNÇÃO DO ORACLE QUE RETORNA 
-- DATA/HORA DO SERVIDOR DE BD
ALTER TABLE T_TESTE_DDL
     MODIFY DT_TESTE DEFAULT SYSDATE;



-- REMOVENDO UMA COLUNA DA TABELA
ALTER TABLE T_TESTE_DDL DROP COLUMN DS_OBS2;

-- REMOVENDO VÁRIAS COLUNAS DA TABELA
ALTER TABLE T_TESTE_DDL DROP (DS_TESTE, DS_OBS1);

-- REMOVENDO CONSTRAINT CHAVE PRIMÁRIA
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT PK_TESTE_DDL;
-- REMOVENDO CONSTRAINT CHAVE PRIMÁRIA COM RELACIONAMENTOS
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT PK_TESTE_DDL CASCADE;

-- REMOVENDO CONSTRAINT CHAVE ESTRANGEIRA
    ALTER TABLE T_TESTE_DDL
DROP CONSTRAINT <FK_NOME_CONSTRAINT_FOREIGN_KEY>;


-- REMOVENDO CONSTRAINT UNIQUE
ALTER TABLE T_TESTE_DDL DROP CONSTRAINT UN_TESTE_DDL_NOME;

-- REMOVENDO CONSTRAINT CHECK
ALTER TABLE T_TESTE_DDL 
DROP CONSTRAINT <CK_NOME_CONSTRAINT_CHECK>;

-- REMOVENDO CONSTRAINT DEFAULT
ALTER TABLE T_TESTE_DDL MODIFY DT_TESTE DEFAULT NULL;


-- RENOMEANDO UMA TABELA
ALTER TABLE T_TESTE_DDL RENAME TO T_TESTE_DDL_NOVO;
                
-- RENOMEANDO UMA COLUNA 
ALTER TABLE T_TESTE_DDL_NOVO RENAME COLUMN
    DS_EMAIL TO DS_EMAIL_NOVO;
    
 -- RENOMEANDO UMA CONSTRAINT
ALTER TABLE T_TESTE_DDL_NOVO RENAME CONSTRAINT
            UN_TESTE_DDL_NOME TO UN_TESTE_DDL_NOME_NOVO;
                                                
-- HABILITANDO CONSTRAINTS
      ALTER TABLE T_TESTE_DDL_NOVO
ENABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;

-- DESABILITANDO CONSTRAINTS
       ALTER TABLE T_TESTE_DDL_NOVO
DISABLE CONSTRAINT UN_TESTE_DDL_NOME_NOVO;

DROP TABLE T_TESTE_DDL_NOVO;