# Generated by Django 5.0.7 on 2024-09-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_nota_nome_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
