# Generated by Django 5.0.4 on 2024-07-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approjeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
