Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2024
Var
// Seção de Declarações das variáveis 
c1, c2 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para c1 := 1 ate 3 faca
     para c2 := 1 ate 3 faca
          escreval (c1, c2)
     fimpara
fimpara

Fimalgoritmo