d = input('digite algo: ')
print('O tipo primitivo é ', type(d))
print('é numerico? ', d.isnumeric())
print('é alfabetico? ', d.isalpha())
print('é decimal? ', d.isdecimal())
print('é um digito? ', d.isdigit())
print('é caixa baixa? ', d.islower())
print('tem espaço? ', d.isspace())
print('é caixa alta?', d.isupper())
print('é alfanumerico? ', d.isalnum())
print('esta capitalizada? ', d.istitle())
